version: 2
jobs:
  install:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

     # Persist everything to make sure we can run the tests in a separate job
      - persist_to_workspace:
          root: ~/repo
          paths:
              - ./
  test:
      docker:
        - image: circleci/node:latest
      working_directory: ~/repo

      steps:
          # Attach workspace with everything in it to run the tests
          - attach_workspace:
              at: ./
          # run tests!
          - run: npm test
          - run:
              # Install the aws cli - We've already set up the required keys
              name: Create production build
              command: rm -rf node_modules && npm install --production
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Package up deployment
          command: zip -r deployment.zip ./*
      - run:
          # Install the aws cli - We've already set up the required keys
          name: Install awscli
          command: sudo pip install awscli
      - run:
          # Deploy everything from the current directory to an S3 bucket
          name: Deploy to S3
          command: aws s3 cp ./deployment.zip s3://health-data-source


# Configure the workflows to only run the deployment on master
workflows:
  version: 2
  install-test-deploy-acceptance:
    jobs:
      - install
      - test:
          requires:
            - install
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
